---
title: "scribblings"
author: "Garrett"
date: "September 25, 2014"
output: html_document
---
This is an important idea, so let's make it clear with a concrete example.

Imagine that you are watching two friends play a game of chance, a corrupted version of liar's dice. Your first friend has a die which he rolls. He then guesses at a number. Your second friend also has a die, which she rolls. She then guesses at a number. Your friends cannot see each other's die, but you can see both dice. Here's what you see

obs | Die A |         | Die B   
--- | ----- | ------- | ------- 
1   | 3     | $\:\:$  | 2       

You can tell that the point of the game is to correctly guess some number related to the values of the dice, but you don't know what that number may be. 





have a pair of dice that you roll repeatedly. On each roll, you record the value of the first die, $D_{1}$, and the value of the second die, $D_{2}$. Your friend, who is standing nearby, also gives you a number to write down, which we will call $S$. After several rolls, you have acquired the following measurements.

&nbsp;|$D_{1}$|$D_{2}$|$S$
:------|--:|--:|--:
Roll 1 | 2 | 6 | 8

&nbsp;|$D_{1}$|$D_{2}$|$S$
:------|--:|--:|--:
Roll 2 | 5 | 4 | 9

&nbsp;|$D_{1}$|$D_{2}$|$S$
:------|--:|--:|--:
Roll 3 | 2 | 1 | 3

&nbsp;|$D_{1}$|$D_{2}$|$S$
:------|--:|--:|--:
Roll 4 | 2 | 3 | 5

You have humored your friend by writing down his number, but now your curiousity is aroused. What is $S$? The measurements above provide an important clue. The values of $D_{1}$, $D_{2}$, and $S$ co-vary in a specific way: the value of $S$ is always equal to the sum of the values of $D_{1}$ and $D_{2}$. You can express this relationship as 

$$S = D_{1} + D_{2}$$

this provides strong evidence that your friend is summing the values of the dice to create $S$. On the next roll, you use this knowledge to predict the value of $S$. You roll a six and a five. Your friend starts to speak, but you cut him off and shout "eleven." He's very impressed! You use the moment to suggest that the two of you find better ways to spend your time.







However, measurements do not make science simpler—they make it more complicated.

When you do this, two surprising phenomena will emerge that shape the worldview of data scientists.

Measurement reveals two things that shape the worldview of data scientists. You can think of these things as the "evil and the cure" when it comes to scientific discovery. One poses a problem for data scientists to solve. The other provides a solution to the problem.

### Variation

First, measurement reveals that the universe is in constant flux. 



If you did not know how $S$ was calculated, you could use this covariation as evidence that $S$ is determined by $D_{1}$

This simple system has an effect, $S$, and two causes, $D_{1}$ and $D_{2}$. I prefer to refer to $S$ as the output of the system. $S$ is determined in a causal manner by $D_{1}$ and $D_{2}$, the inputs of the system. If you change the value of $D_{1}$ or $D_{2}$, the value of $S$ will change in response. If you collect data on the system, the causal relationship would appear as a strong covariation between $S$, $D_{1}$, and $D_{2}$. Whenever the values of $D_{1}$ and $D_{2}$ are high, the value of S will be high. Whenever the values of $D_{1}$ and $D_{2}$ are low, the value of $S$ will be low.

Whenever a set of variables determines the value of an output variable, you can express the relationship as a formula, like $S = D_{1} + D_{2}$. For convenience, I'm going to call this type of formula a _scientific law_. These formulas are scientific because they deal with quantities or qualities that can be observed (at least in theory). These formulas are laws because they describe law-like relationships. The relationship must always hold so long as the set of input variables _does_ determine the value of the output variable in a causal manner.

### Scientific laws

You've seen scientific laws in many places. For example, two familiar scientific laws are 

$$E=Mc^{2}$$

and 

$$F=MA$$

The first law states that the energy content of a system ($E$) is equal to the mass of the system ($M$) multiplied by the speed of light squared ($c^{2}$). The second law explains that force exerted upon an object ($F$) is equal to the mass of the object ($M$) multiplied by its acceleration ($A$). 

In theses laws, the quantities $E$, $M$, $F$, and $A$ are all variables. The quantity $c$ is a constant value, in theory.

Scientists search for scientific laws because laws provide a way to reason about variation. Laws explain why and how the values of a variable vary. They also help scientists understand, predict, and control natural behavior.

First, you can use a law to understand the world. $E = Mc^{2}$ explains why plutonium creates a nuclear explosion when detonated. A piece of plutonium contains an amount of energy equal to the mass of the piece times the speed of light squared. When plutonium is detonated, an atomic reaction converts some of this mass to energy. Scientists have used the law to calculate that about one gram of plutonium was converted to energy when the United States detonated a plutonium bomb above Nagasaki, Japan in WWII. One gram of plutonium would weigh about as much as a paper clip.

Second, you can use a law to make predictions. For example, you could use the law $F = MA$ to predict how fast a nuclear bomb will accelerate once you drop it out of a plane. Substitute the force exerted by gravity for $F$, the mass of the bomb for $M$, and then do some simple algebra to get $A$.

Third, you can use a scientific law to control a system. Imagine that you would like to design a plane that can accelerate fast enough after dropping a nuclear bomb to escape the resulting explosion. The law $F = MA$ tells you how to do this. You can make a plane accelerate faster by decreasing its mass or by giving it an engine that can exert more force on the plane. Given this application, I’d do both.



Variation shapes the worldview of data scientists. Data scientists treat everything that can be measured as a _variable_, a quantity or quality whose value can vary from measurement to measurement.



To summarize, variation is an omnipresent phenomenon that creates uncertainty. It is difficult to know what value you will observe when you measure a quantity—even if you have measured the quantity before.

### The goal of data science

Variation creates a goal for data scientists. Data scientists try to understand the variation that is associated with a variable. This helps data scientists

1. Explain why the values of a variable vary
2. Predict which values a variable will take under different sets of conditions
3. Control the value of a variable by manipulating the conditions that affect it

"Variable" is an abstract, mathematical term. So these goals may seem abstract and mathematical, but they are not. You can use data science to explain, predict, and perhaps control anything that you can measure.

For example, you can use data science to identify an effective treatment for bone cancer, to explain why annual rainfall in the midwest varies from year to year, and to determine whether the housing market has entered another economic bubble.

Data scientists build insights about variation by looking for structure within variation.

Take, for example, a simple variable, like the acceleration of a particle in space. You can measure the particle's acceleration under different conditions. Sometimes the particle will be acclerating rapidly, sometimes it will be slowing down, sometimes it will not be accelerating at all. In other words, the acceleration can vary widely as different forces act on the particle. However, 

Variation is not haphazard, but has structure. If you examine multiple measurements of the same variable, you will notice that some values appear more often than others. For example, if you measure the heights of adult men, you will notice that many men are roughly 5' 9&rdquo; (~175 cm). A much smaller number of men are a foot taller (6' 9&rdquo;) or a foot shorter (4' 9&rdquo;), and almost nobody is two feet taller (7' 9&rdquo;) or two feet shorter (3' 9&rdquo;).

For every variable, some values will seem typical; some values will seem rare but plausible; and other values will seem downright impossible. In other words, the possible values of each variable are distributed in a structured way. You can improve your predictions about a variable if you identify the distribution of values associated with the variable.

In other words, if you repeatedly measure both the acceleration ($A$) and forces acting upon the particle ($F$), each variable would display a pattern of variation. (Let's disregard the mass of the particle for now, since its presumably constant).

If you measured not just the acceleration of the particle ($A$), but also the mass of the particle ($M$) and the forces acting upon it ($F$), each variable would display a pattern of variation. (The pattern of the mass would presumably be no variation since the mass stays constant). Moreover, the values of one variable would correspond to the values of the other variables in a systematic way. Whenever you measure the three variables simultaneously, their values will display the relationship $F = MA$.

If you collect multiple measurements of _several_ variables, you may notice a second type of structure. The values of one variable may correspond to the values of another variable in a systematic way. For example, if you measured the heights and weights of children, you may notice that children with large heights also tend to have large weights, and vice versa. 

This correspondence between variables is known as _covariation_, and it provides a way to discover natural laws. If two variables are related through a natural law, the relationship described in the law will appear whenever you measure the two variables together. As a result, the values of the variables will covary.

